-- Clear existing categories and insert new ones
DELETE FROM public.categories;

INSERT INTO public.categories (id, name, display_order) VALUES
('ACCES', 'Accesorios', 1),
('DIADE', 'Diademas', 2),
('DIGIT', 'Proyectores, Tablets y Scanners', 3),
('REFCA', 'Refacciones - Cargadores', 4),
('REFBA', 'Refacciones - Baterías', 5),
('REFPA', 'Refacciones - Pantallas', 6),
('REFTE', 'Refacciones - Teclados', 7),
('REFOT', 'Refacciones - Otros', 8),
('MOBIL', 'Mobiliario', 9),
('LAPTO', 'Laptops', 10),
('COMPU', 'Computadoras de Escritorio', 11),
('ENREG', 'Reguladores', 12),
('ENNOB', 'No-Breaks', 13),
('ENOTS', 'Power Banks y Multicontactos', 14),
('SOFTW', 'Software y Licencias', 15),
('RUBIQ', 'Redes Ubiquiti', 16),
('RTPLK', 'Redes TP-Link', 17),
('REDOT', 'Redes Otras Marcas', 18),
('CARED', 'Cables de Red', 19),
('CABOT', 'Cables Varios', 20),
('MONIT', 'Monitores', 21),
('TECLA', 'Teclados', 22),
('MOUSE', 'Mouse', 23),
('BOCIN', 'Bocinas', 24),
('DDURI', 'Discos Duros Internos', 25),
('DDURE', 'Discos Duros Externos', 26),
('CONHP', 'Consumibles HP', 27),
('CONEP', 'Consumibles Epson', 28),
('CONOT', 'Consumibles Otros', 29),
('MEUSB', 'Memorias USB', 30),
('MESOD', 'Memorias SODIMM', 31),
('MEDIM', 'Memorias DIMM', 32),
('MEFLA', 'Memorias Flash', 33),
('IMPEP', 'Impresoras Epson', 34),
('IMPHP', 'Impresoras HP', 35),
('IMPOT', 'Impresoras Otras', 36),
('MICRO', 'Procesadores', 37),
('MOTHE', 'Motherboards', 38),
('GABIN', 'Gabinetes', 39),
('PTVTA', 'Punto de Venta', 40),
('VIDEO', 'Tarjetas de Video', 41),
('MIKRO', 'Mikrotik', 42),
('SEGUR', 'CCTV y Seguridad', 43),
('PROMO', 'Promociones', 44),
('COMUN', 'Comunicación', 45);