
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ncufwwlxwastsgdqmpaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jdWZ3d2x4d2FzdHNnZHFtcGFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5MDI2MjYsImV4cCI6MjA1NzQ3ODYyNn0.Mjb4XffVeFB0c2FrwxLloFr50DXvZLuBx72EuGc_mDY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
